### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by mairacanal** [toradex/rt-validation#1]
Currently, the repository has no LICENSE file or copyright indication. I'm using these tools on my undergrad research project and I was looking for the tool's LICENSE to mention on my project. Is there any LICENSE for this repository?

**Comment by charles2910** [comment]
Hi, Maíra.

Thanks for bringing this up. The license for this repository is MIT. We are currently working on adding it and soon it will reach this repo.

Cheers

**Comment by charles2910** [comment]
I believe this issue can be closed now. c029b0f46312b93345c526ed24dbbb812f329b94 adds a license to the project.
