### ISSUE TITLE
stress-tests.sh replaces file.tar

### ISSUE THREAD

**Issue by jo-so-nx** [toradex/rt-validation#2]
Why do I have to provide a file.tar (see [Prepare device](https://github.com/toradex/rt-validation#prepare-the-device-for-the-tests)) while the file gets created in [stress-tests.sh:16](https://github.com/toradex/rt-validation/blob/e584896f5ae2b06e5aca71cc90568b6c4f390b93/stress-tests/stress-tests.sh#L16)? On my system, the directory /var/log is nearly empty. Hence, this doesn't really provide any data.

**Comment by leograba** [comment]
Hello @jo-so-nx,

Thanks for reporting the issue. If you want to propose a solution as a PR, we'll gladly review and merge it, otherwise, I will capture this as a bug in our internal issue tracker.

Best regards.

**Comment by leonheldattoradex** [comment]
#3 closed due to merge in `torizon-containers`. 
See #3 for more information.
